### ISSUE TITLE
Cannot install Massif nor EMF-IncQuery: version compatibility issue?

### ISSUE THREAD

**Issue by devauxt** [FTSRG/massif#45]
Hello,
I am very interrested in testing your Massif tool; from what I understood it may fit exaclty our need (wordwide automotive supplier).

Unfortunately I am quite new to the Eclipse world and probably missing something when installing.

I cannot install Massif neither than EMF-IncQUery: I tried several versions of Eclipse, from Neon to Keppler, and several version of EMF_IncQUery also. I always end-up with the same kind of issue with Massif or EMF-IncQUery 

Example when installing Massif from local download, I get this:
![cannotperformoperation](https://cloud.githubusercontent.com/assets/20838558/17428739/003a7c16-5aeb-11e6-958d-db4ff6ee0f7d.png)

Then the following errors:
Cannot complete the install because one or more required items could not be found.
  Software being installed: Massif Simulink UI Feature 0.6.0.201606140209 (hu.bme.mit.massif.simulink.ui.feature.group 0.6.0.201606140209)
  Missing requirement: Simulink Model 0.6.0.201606140209 (hu.bme.mit.massif.simulink 0.6.0.201606140209) requires 'bundle org.eclipse.viatra.query.runtime [1.2.0,2.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Simulink API 0.6.0.201606140209 (hu.bme.mit.massif.simulink.api 0.6.0.201606140209)
    To: bundle hu.bme.mit.massif.simulink 0.0.0
  Cannot satisfy dependency:
    From: Massif Simulink API Feature 0.6.0.201606140209 (hu.bme.mit.massif.simulink.api.feature.group 0.6.0.201606140209)
    To: hu.bme.mit.massif.simulink.api [0.6.0.201606140209]
  Cannot satisfy dependency:
    From: Massif Simulink UI Feature 0.6.0.201606140209 (hu.bme.mit.massif.simulink.ui.feature.group 0.6.0.201606140209)
    To: hu.bme.mit.massif.simulink.api.feature.group [0.6.0.201606140209]

I somebody have some ideas to help me, please share!

Thanks,

Thomas.

**Comment by abelhegedus** [comment]
Hi Thomas,

> Missing requirement: Simulink Model 0.6.0.201606140209 (hu.bme.mit.massif.simulink 0.6.0.201606140209) requires 'bundle org.eclipse.viatra.query.runtime [1.2.0,2.0.0)' but it could not be found

It seems you are trying to use the newest, unreleased version of Massif, that depends on VIATRA instead of EMF-IncQuery (the reasons are detailed here: http://viatra.net/news/2016/2/say-goodbye-to-emf-incquery-say-hello-to-viatra-query ). Unfortunately, we have not yet updated the documentation for Massif after this move.

So, if you want to install the current version of Massif 0.6.0, use http://download.eclipse.org/viatra/incquery/updates/release to install the required dependencies from VIATRA.

Cheers

**Comment by devauxt** [comment]
Thank you for the anwser,

I tried this (believe I had alreardy try in my numerous tentative before) and get same issues: cannot complete VIATRA neither than Massif

With VIATRA I get:
Your original request has been modified.
  "Google Guice (No AOP)" will be ignored because a newer version is already installed. 
  "Google Guice Multibindings Source" will be ignored because a newer version is already installed. 
Cannot complete the install because one or more required items could not be found.
  Software being installed: GMF Support for EMF-IncQuery Developer Resources 1.1.0.201512031022 (org.eclipse.incquery.runtime.gmf.feature.source.feature.group 1.1.0.201512031022)
  Missing requirement: IncQuery GMF Integration 1.1.0.201512031022 (org.eclipse.incquery.runtime.gmf 1.1.0.201512031022) requires 'bundle org.eclipse.gmf.runtime.notation 1.4.1' but it could not be found
  Cannot satisfy dependency:
    From: GMF Support for EMF-IncQuery 1.1.0.201512031022 (org.eclipse.incquery.runtime.gmf.feature.feature.group 1.1.0.201512031022)
    To: org.eclipse.incquery.runtime.gmf [1.1.0.201512031022]
  Cannot satisfy dependency:
    From: GMF Support for EMF-IncQuery Developer Resources 1.1.0.201512031022 (org.eclipse.incquery.runtime.gmf.feature.source.feature.group 1.1.0.201512031022)
    To: org.eclipse.incquery.runtime.gmf.feature.feature.group [1.1.0.201512031022]

With Massif I get:
Cannot complete the install because one or more required items could not be found.
  Software being installed: Massif Simulink UI Feature 0.6.0.201606140209 (hu.bme.mit.massif.simulink.ui.feature.group 0.6.0.201606140209)
  Missing requirement: Simulink Model 0.6.0.201606140209 (hu.bme.mit.massif.simulink 0.6.0.201606140209) requires 'bundle org.eclipse.viatra.query.runtime [1.2.0,2.0.0)' but it could not be found
  Cannot satisfy dependency:
    From: Simulink API 0.6.0.201606140209 (hu.bme.mit.massif.simulink.api 0.6.0.201606140209)
    To: bundle hu.bme.mit.massif.simulink 0.0.0
  Cannot satisfy dependency:
    From: Massif Simulink API Feature 0.6.0.201606140209 (hu.bme.mit.massif.simulink.api.feature.group 0.6.0.201606140209)
    To: hu.bme.mit.massif.simulink.api [0.6.0.201606140209]
  Cannot satisfy dependency:
    From: Massif Simulink UI Feature 0.6.0.201606140209 (hu.bme.mit.massif.simulink.ui.feature.group 0.6.0.201606140209)
    To: hu.bme.mit.massif.simulink.api.feature.group [0.6.0.201606140209]

**Comment by abelhegedus** [comment]
> org.eclipse.incquery.runtime.gmf.feature.source.feature.group 1.1.0.201512031022
Okay, it seems that you have are still trying to install EMF-IncQuery and not VIATRA. Check in `Window -> Installation details -> Installed Features` and uninstall all EMF-IncQuery related items, if there are any.

You have two options:
- install EMF-IncQuery 1.0.0 from http://download.eclipse.org/viatra/incquery/updates/release and Massif 0.5.0 release from http://static.incquerylabs.com/projects/massif/release/0.4.0-0.5.0/repository
- install VIATRA 1.2.0 from http://download.eclipse.org/viatra/updates/release/ and Massif 0.6.0 integration from http://static.incquerylabs.com/projects/massif/integration/

Note that if you install the EMF-IncQuery 1.0.0 SDK, you need Xtext 2.8.x installed, while for VIATRA 1.2.0 Query SDK, you need Xtext 2.9.x.

Since VIATRA 1,3,0 has been released, I will create Massif 0.6.0 release targeting VIATRA 1.2.0 and update Massif to be compatible with VIATRA 1.3.0 release as well.

**Comment by devauxt** [comment]
Hello,
Well this worked perfectly (VIATRA 1.2.0 and Massif 0.6.0)!

After that I faced some issues with the connection to Matlab; but finally I got the Command Evaluation Server solution to work (by reinstalling java jre). 

Now I will try use it ;)
Thanks for the support.

Thomas.

**Comment by abelhegedus** [comment]
Great to hear that, looking forward to your feedback.
